---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: game-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: game-server
  policy:
    semver:
      range: 1.x

