---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: game-server
  namespace: flux-system
spec:
  checkout:
    branch: master
    gitRepositoryRef:
      name: game-server
  commit:
    authorEmail: nithinreddy2994@gamil.com
    authorName: Nithin2994
    messageTemplate: 'auto commit'
  interval: 1m0s