---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: game-server
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/Nithin2994/GameServer-golang

