apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: game-server-golang
  namespace: flux-system
spec:
  checkout:
    branch: master
    gitRepositoryRef:
      name: game-server-golang
  commit:
    authorEmail: fluxcdbot@particule.io
    authorName: fluxcdbot
    messageTemplate: 'update image'
  interval: 1m0s
  update:
    strategy: Setters