---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: gameserver-golang-image-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: nithinreddy2994@gamil.com
        name: Nithin2994
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main-push
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system

